import Head from "next/head";
import { Banner } from "@/components/Banner";
import RowSlider, { RecommendationWidget } from "@/components/SectionWrapper";
import { CommentWrapper } from "@/components/CommentSection";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>AnimeTV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <RowSlider title="Trending" fetchUrl={"fetchTrending"} />
        <RowSlider
          title="Netflix Original"
          fetchUrl={"fetchNetflixOriginals"}
          isLargeRow
        />
        <div className="bg-cyan-100 dark:bg-darkTheme-800 w-full h-full flex flex-col lg:flex-row justify-center lg:items-start items-center">
          <CommentWrapper />
          <RecommendationWidget />
        </div>
      </main>
    </>
  );
}
