import Head from "next/head";
import { Banner } from "@/components/Banner";

export default function Home() {
  return (
    <>
      <Head>
        <title>AnimeTV</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <div className="h-screen w-full flex-col gap-32 flex justify-center items-center"></div>
      </main>
    </>
  );
}
